# Generated by Django 6.0.7 on 2026-07-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("pinterest", "Pinterest"),
                            ("threads", "Threads"),
                        ],
                        max_length=20,
                    ),
                ),
                ("impressions", models.IntegerField(blank=True, null=True)),
                ("reach", models.IntegerField(blank=True, null=True)),
                ("engagements", models.IntegerField(blank=True, null=True)),
                ("likes", models.IntegerField(blank=True, null=True)),
                ("comments", models.IntegerField(blank=True, null=True)),
                ("shares", models.IntegerField(blank=True, null=True)),
                ("clicks", models.IntegerField(blank=True, null=True)),
                ("video_views", models.IntegerField(blank=True, null=True)),
                ("video_completions", models.IntegerField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_metrics",
                        to="content.contentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyBusinessMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_impressions", models.IntegerField(default=0)),
                ("total_reach", models.IntegerField(default=0)),
                ("total_engagements", models.IntegerField(default=0)),
                ("total_followers", models.IntegerField(blank=True, null=True)),
                ("platform_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "unique_together": {("business", "date")},
            },
        ),
    ]
