# Generated by Django 6.0.7 on 2026-07-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("business", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ContentDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_copy", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_content_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField()),
                ("comments", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_approvals_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="content.contentdraft",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("scheduled_date", models.DateField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("pinterest", "Pinterest"),
                            ("threads", "Threads"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("draft", "Draft"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                ("copy", models.TextField(blank=True)),
                ("image_prompt", models.TextField(blank=True)),
                ("video_prompt", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_items",
                        to="content.contentcalendar",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "platform"],
            },
        ),
        migrations.AddField(
            model_name="contentdraft",
            name="content_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="content.contentitem",
            ),
        ),
        migrations.CreateModel(
            name="ContentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="content_assets/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("prompt_used", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="content.contentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentPublishLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter/X"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("pinterest", "Pinterest"),
                            ("threads", "Threads"),
                        ],
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("external_post_id", models.CharField(blank=True, max_length=255)),
                ("external_url", models.URLField(blank=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_logs",
                        to="content.contentitem",
                    ),
                ),
            ],
        ),
    ]
